import Link from "next/link";
import { ArrowRight, Check, FileCheck2, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/logo";
import { WalletControl } from "@/components/wallet-control";

export default function Landing() {
  return <main className="min-h-screen overflow-hidden bg-[#08111F] text-white">
    <nav className="mx-auto flex max-w-[1320px] items-center justify-between px-6 py-6 lg:px-10"><Logo dark/><div className="hidden items-center gap-8 text-sm text-[#91A0B4] md:flex"><Link href="/dashboard" className="hover:text-white">Operations</Link><Link href="/claims" className="hover:text-white">Claims</Link><Link href="/evidence" className="hover:text-white">Evidence</Link></div><WalletControl dark/></nav>
    <section className="relative mx-auto grid min-h-[calc(100vh-88px)] max-w-[1320px] items-center gap-16 px-6 py-16 lg:grid-cols-[1.03fr_.97fr] lg:px-10"><div className="page-reveal relative z-10"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-3 py-1.5 text-[11px] text-[#A6B4C6]"><ShieldCheck size={14} className="text-[#4D8DFF]"/>Evidence-led insurance claim resolution</div><h1 className="max-w-[680px] text-5xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-6xl xl:text-[74px]">Insurance claims,<br/><span className="text-[#9FC0FF]">resolved with evidence.</span></h1><p className="mt-7 max-w-[610px] text-base leading-7 text-[#98A8BC] sm:text-lg">ClaimGuard transforms policy terms, incident records, supporting evidence, and loss documentation into structured, auditable claim decisions.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/claims" className="btn-primary !px-5 !py-3.5">Review claims <ArrowRight size={16}/></Link><Link href="/claims/new" className="rounded-[11px] border border-white/15 px-5 py-3.5 text-sm font-semibold hover:bg-white/5">Create a claim</Link></div><div className="mt-14 flex flex-wrap gap-x-8 gap-y-3 text-xs text-[#708197]"><span className="flex items-center gap-2"><Check size={14} className="text-[#21C58E]"/>Structured evidence trails</span><span className="flex items-center gap-2"><Check size={14} className="text-[#21C58E]"/>Auditable recommendations</span></div></div><ClaimPreview/></section>
  </main>;
}

function ClaimPreview() {
  return <div className="page-reveal relative mx-auto w-full max-w-[570px] [animation-delay:.12s]"><div className="absolute -inset-24 bg-[radial-gradient(circle,rgba(77,141,255,.14),transparent_64%)]"/><div className="relative overflow-hidden rounded-[18px] border border-white/10 bg-[#0B1628] shadow-[0_38px_90px_rgba(0,0,0,.38)]"><div className="flex items-center justify-between border-b border-white/8 px-6 py-5"><div><p className="text-[10px] uppercase tracking-[.15em] text-[#64768E]">Motor claim</p><h2 className="mt-1 text-base font-semibold">#CG-20481</h2></div><span className="rounded-full bg-[#14362F] px-3 py-1.5 text-[11px] text-[#65DEB5]">Decision ready</span></div><div className="p-6"><p className="text-xs text-[#788BA4]">Comprehensive Motor</p><div className="mt-6 grid grid-cols-2 gap-x-8 gap-y-6"><Info label="Claimed" value="₦1,850,000"/><Info label="Evidence strength" value="Strong" green/><Info label="Coverage confidence" value="92%"/><Info label="Recommended settlement" value="₦1,640,000" large/></div><div className="mt-7 border-t border-white/8 pt-5"><div className="mb-3 flex items-center gap-2 text-xs text-[#8092A8]"><FileCheck2 size={14}/>Evidence record</div><div className="flex flex-wrap gap-2">{["Police Report","Damage Photos","Repair Estimate","Policy Schedule"].map(x=><span key={x} className="rounded-lg border border-white/8 bg-white/[.035] px-2.5 py-2 text-[10px] text-[#B5C0CE]">{x}</span>)}</div></div><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full w-[92%] rounded-full bg-[#4D8DFF]"/></div></div></div></div>;
}

function Info({label,value,green,large}:{label:string;value:string;green?:boolean;large?:boolean}) {
  return <div><p className="text-[10px] uppercase tracking-[.1em] text-[#63758D]">{label}</p><p className={`mt-2 font-semibold tracking-[-.035em] ${green?"text-[#65DEB5]":"text-white"} ${large?"text-xl":"text-lg"}`}>{value}</p></div>;
}
