"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { AlertTriangle,Calculator,CheckCircle2,FileCheck2,Scale } from "lucide-react";
import { AppShell } from "./app-shell";
import { EvidencePreviewModal } from "./evidence-preview-modal";
import { StatusBadge } from "./status-badge";
import { useClaims } from "./claims-provider";
import { useDecisions } from "./decisions-provider";
import { claimEvidenceItems,type EvidenceRepositoryItem } from "@/lib/evidence-data";
import { calculateCoverage,createDecision,finalizeDecision,type ClaimDecision,type DecisionChoice,type EvidenceRelevance,type EvidenceReviewStatus } from "@/lib/decision-types";
import { naira } from "@/lib/data";
import { shortenAddress } from "@/lib/wallet";

const reviewStatuses:EvidenceReviewStatus[]=["Unverified","Verified","Reviewed","Needs attention","Rejected evidence"];
const relevances:EvidenceRelevance[]=["High","Medium","Low"];
const choices:DecisionChoice[]=["Approve","Partial approval","Request more evidence","Reject"];
type Errors=Record<string,string>;

export function DecisionWorkspace({id}:{id:string}){const {findLocalClaim}=useClaims();const {findDecision,saveDecision}=useDecisions();const claim=findLocalClaim(id);if(!claim)return <SeededDecision id={id}/>;return <LocalDecision key={id} claim={claim} initial={findDecision(id)??createDecision(claim)} save={saveDecision}/>}

function LocalDecision({claim,initial,save}:{claim:NonNullable<ReturnType<ReturnType<typeof useClaims>["findLocalClaim"]>>;initial:ClaimDecision;save:(decision:ClaimDecision)=>void}){
  const [decision,setDecision]=useState<ClaimDecision>(()=>({...initial,coverage:{...calculateCoverage(claim),completedAt:initial.coverage.completedAt}}));const [selected,setSelected]=useState<EvidenceRepositoryItem|null>(null);const [errors,setErrors]=useState<Errors>({});const close=useCallback(()=>setSelected(null),[]);const evidence=useMemo(()=>claimEvidenceItems(claim).map(item=>{const review=decision.evidenceReviews.find(value=>value.evidenceId===item.id.split(":").slice(1).join(":"));return {...item,status:review?.status??item.status,relevance:review?.relevance??item.relevance}}),[claim,decision.evidenceReviews]);
  useEffect(()=>{if(process.env.NODE_ENV==="development"&&claim.id==="CG-15183")console.info("[ClaimGuard coverage diagnostic]",{claimId:claim.id,incidentDate:claim.incident?.incidentDate??null,policyStartDate:claim.policy?.policyStartDate??null,policyEndDate:claim.policy?.policyEndDate??null})},[claim]);
  const commit=(next:ClaimDecision)=>{setDecision(next);save(next)};const activity=(value:ClaimDecision,message:string,type:string)=>({...value,activities:[{id:crypto.randomUUID(),message,type,createdAt:new Date().toISOString()},...value.activities]});
  const reviewEvidence=(evidenceId:string,patch:{status?:EvidenceReviewStatus;relevance?:EvidenceRelevance;reviewerNote?:string})=>{const id=evidenceId.split(":").slice(1).join(":");const existing=decision.evidenceReviews.find(item=>item.evidenceId===id);const review={evidenceId:id,status:existing?.status??"Unverified" as EvidenceReviewStatus,relevance:existing?.relevance??"Medium" as EvidenceRelevance,reviewerNote:existing?.reviewerNote??"",updatedAt:new Date().toISOString(),...patch};let next:ClaimDecision={...decision,workflowStatus:"Evidence Review",evidenceReviews:[...decision.evidenceReviews.filter(item=>item.evidenceId!==id),review]};if(!decision.activities.some(item=>item.type==="review-started"))next=activity(next,"Evidence review started","review-started");if(patch.status&&patch.status!==existing?.status)next=activity(next,`Evidence item marked ${patch.status.toLowerCase()}`,"evidence-reviewed");commit(next)};
  const completeCoverage=()=>{let next:ClaimDecision={...decision,workflowStatus:"Coverage Analysis",coverage:{...calculateCoverage(claim),completedAt:new Date().toISOString()}};next=activity(next,"Coverage analysis completed","coverage-completed");commit(next)};
  const validate=()=>{const next:Errors={};const choice=decision.choice;if(!choice)next.choice="Select a decision recommendation.";if(choice==="Approve"&&(decision.recommendedSettlement<=0||decision.recommendedSettlement>decision.coverage.netEligibleAmount))next.settlement=`Settlement must be greater than zero and no more than ${naira(decision.coverage.netEligibleAmount)}.`;if(choice==="Partial approval"){if(decision.recommendedSettlement<=0||decision.recommendedSettlement>decision.coverage.netEligibleAmount)next.settlement=`Settlement must be greater than zero and no more than ${naira(decision.coverage.netEligibleAmount)}.`;if(!decision.rationale.trim())next.rationale="A rationale is required for partial approval."}if(choice==="Request more evidence"&&!decision.requiredEvidenceMessage.trim())next.requiredEvidence="Enter the additional evidence request.";if(choice==="Reject"&&!decision.rationale.trim())next.rationale="A rationale is required for rejection.";setErrors(next);return Object.keys(next).length===0};
  const finalize=()=>{if(!validate()||!decision.choice)return;const messages:Record<DecisionChoice,string>={Approve:"Claim approved","Partial approval":"Claim partially approved","Request more evidence":"Additional evidence requested",Reject:"Claim rejected"};commit(finalizeDecision(activity(decision,messages[decision.choice],"decision-finalized")))};
  const setChoice=(choice:DecisionChoice)=>{let next:ClaimDecision={...decision,choice,recommendedSettlement:["Reject","Request more evidence"].includes(choice)?0:decision.recommendedSettlement,workflowStatus:"Decision Ready"};if(!decision.activities.some(item=>item.type==="decision-prepared"))next=activity(next,"Decision prepared","decision-prepared");commit(next)};
  return <AppShell title={`Decision · ${claim.id}`} subtitle="Coverage review and settlement preparation"><div className="page-reveal space-y-6">
    <header className="panel flex flex-wrap items-start gap-6 p-6"><span className="grid size-12 place-items-center rounded-xl bg-[#0B1628] text-white"><Scale size={21}/></span><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-semibold">Claim {claim.id}</h2><StatusBadge status={decision.workflowStatus}/></div><p className="mt-2 text-sm text-[#718094]">{claim.incident.incidentType} · {claim.policy.coverageType}</p></div><div className="ml-auto grid gap-4 sm:grid-cols-3"><Fact label="Claimant wallet" value={claim.walletAddress?shortenAddress(claim.walletAddress):"Guest"}/><Fact label="Submitted" value={new Date(claim.review.submittedAt).toLocaleString("en-NG")}/><Fact label="Requested" value={naira(claim.financialLoss.requestedAmount)}/></div></header>
    <section className="panel p-6"><SectionHeader number="01" title="Claim summary"/><div className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><Fact label="Incident" value={`${claim.incident.incidentType} · ${claim.incident.incidentDate}`}/><Fact label="Insured asset" value={claim.policy.insuredAsset}/><Fact label="Policy number" value={claim.policy.policyNumber}/><Fact label="Insurer" value={claim.policy.insurer}/><Fact label="Deductible" value={naira(claim.policy.deductible)}/><Fact label="Coverage limit" value={naira(claim.policy.coverageLimit)}/><Fact label="Location" value={claim.incident.location}/><Fact label="Submission time" value={new Date(claim.review.submittedAt).toLocaleString("en-NG")}/></div></section>
    <section className="panel overflow-hidden"><div className="p-6"><SectionHeader number="02" title="Evidence review" detail="Claimant uploads remain unverified until a reviewer assigns a status."/></div><div className="divide-y divide-[#E4EAF1]">{evidence.length?evidence.map(item=>{const recordId=item.id.split(":").slice(1).join(":");const review=decision.evidenceReviews.find(value=>value.evidenceId===recordId);return <article key={item.id} className="grid gap-4 p-6 xl:grid-cols-[minmax(260px,1fr)_190px_150px_minmax(240px,.8fr)]"><button type="button" onClick={()=>setSelected(item)} className="flex min-w-0 items-start gap-3 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#4D8DFF]"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#EDF4FF] text-[#326DCA]"><FileCheck2 size={17}/></span><span className="min-w-0"><span className="block font-semibold">{item.title}</span><span className="mt-1 block truncate text-xs text-[#718094]">{item.filename} · {item.source}</span></span></button><label><span className="label">Review status</span><select className="field" value={review?.status??"Unverified"} onChange={event=>reviewEvidence(item.id,{status:event.target.value as EvidenceReviewStatus})}>{reviewStatuses.map(value=><option key={value}>{value}</option>)}</select></label><label><span className="label">Relevance</span><select className="field" value={review?.relevance??"Medium"} onChange={event=>reviewEvidence(item.id,{relevance:event.target.value as EvidenceRelevance})}>{relevances.map(value=><option key={value}>{value}</option>)}</select></label><label><span className="label">Reviewer note</span><input className="field" value={review?.reviewerNote??""} onChange={event=>reviewEvidence(item.id,{reviewerNote:event.target.value})} placeholder="Internal evidence note"/></label></article>}):<p className="p-6 text-sm text-[#718094]">No evidence was supplied with this claim.</p>}</div></section>
    <section className="panel p-6"><SectionHeader number="03" title="Coverage analysis" detail="Deterministic policy arithmetic only; this does not establish claim legitimacy."/><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><CoverageFlag label="Policy active on incident date" value={decision.coverage.policyActive}/><CoverageFlag label="Incident within coverage period" value={decision.coverage.incidentWithinCoveragePeriod}/><Amount label="Requested amount" value={decision.coverage.requestedAmount}/><Amount label="Documented loss" value={decision.coverage.documentedLoss}/><Amount label="Deductible" value={decision.coverage.deductible}/><Amount label="Coverage limit" value={decision.coverage.coverageLimit}/><Amount label="Eligible loss" value={decision.coverage.eligibleLoss}/><Amount label="Maximum payable amount" value={decision.coverage.netEligibleAmount} accent/></div><div className="mt-5 flex justify-end"><button type="button" onClick={completeCoverage} className="btn-secondary"><Calculator size={15}/>{decision.coverage.completedAt?"Recalculate coverage":"Complete coverage analysis"}</button></div></section>
    <section className="panel p-6"><SectionHeader number="04" title="Decision preparation"/><fieldset className="mt-5"><legend className="label">Recommendation</legend><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{choices.map(choice=><button type="button" key={choice} onClick={()=>setChoice(choice)} className={`min-h-12 rounded-xl border px-4 text-sm font-semibold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#4D8DFF] ${decision.choice===choice?"border-[#8DB4FF] bg-[#F1F6FF] text-[#245FAF]":"border-[#D6DFEA] bg-white text-[#526177] hover:border-[#9DBCF0]"}`}>{choice}</button>)}</div><ErrorText>{errors.choice}</ErrorText></fieldset><div className="mt-6 grid gap-5 md:grid-cols-2"><label><span className="label">Recommended settlement amount</span><input className="field" type="number" min="0" disabled={decision.choice==="Reject"||decision.choice==="Request more evidence"} value={decision.recommendedSettlement} onChange={event=>commit({...decision,recommendedSettlement:Number(event.target.value)})}/><ErrorText>{errors.settlement}</ErrorText></label><label><span className="label">Decision rationale</span><textarea className="field min-h-28 resize-y" value={decision.rationale} onChange={event=>commit({...decision,rationale:event.target.value})}/><ErrorText>{errors.rationale}</ErrorText></label><label><span className="label">Internal reviewer notes</span><textarea className="field min-h-28 resize-y" value={decision.internalNotes} onChange={event=>commit({...decision,internalNotes:event.target.value})}/></label><label><span className="label">Required evidence / request message</span><textarea className="field min-h-28 resize-y" value={decision.requiredEvidenceMessage} onChange={event=>commit({...decision,requiredEvidenceMessage:event.target.value})}/><ErrorText>{errors.requiredEvidence}</ErrorText></label></div><div className="mt-6 flex justify-end"><button type="button" onClick={finalize} className="btn-primary"><CheckCircle2 size={16}/>Save decision</button></div></section>
  </div>{selected&&<EvidencePreviewModal item={selected} onClose={close}/>}</AppShell>;
}

function SeededDecision({id}:{id:string}){return <AppShell title={`Decision · ${id}`} subtitle="Seeded decision demonstration"><div className="page-reveal panel p-8"><p className="eyebrow">Demonstration record</p><h2 className="mt-3 text-2xl font-semibold">Existing seeded decision</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#718094]">This is preserved seeded data. Functional review controls are available for locally submitted claims from the <Link href="/decisions" className="font-semibold text-[#326DCA]">Decision Operations queue</Link>.</p></div></AppShell>}
function SectionHeader({number,title,detail}:{number:string;title:string;detail?:string}){return <div><div className="flex items-center gap-3"><span className="font-mono text-[11px] font-semibold text-[#4D8DFF]">{number}</span><h2 className="text-base font-semibold">{title}</h2></div>{detail&&<p className="mt-2 text-xs leading-5 text-[#718094]">{detail}</p>}</div>}
function Fact({label,value}:{label:string;value:string}){return <div className="min-w-0"><p className="text-[10px] uppercase tracking-[.08em] text-[#8A96A6]">{label}</p><p className="mt-1.5 break-words text-xs font-semibold text-[#344359]">{value}</p></div>}
function Amount({label,value,accent=false}:{label:string;value:number;accent?:boolean}){return <div className={`rounded-xl border p-4 ${accent?"border-[#9EC1FA] bg-[#F1F6FF]":"border-[#E1E7EF] bg-[#FAFBFD]"}`}><p className="text-[10px] uppercase tracking-[.08em] text-[#8491A2]">{label}</p><p className={`mt-2 text-lg font-semibold tabular-nums ${accent?"text-[#245FAF]":"text-[#223147]"}`}>{naira(value)}</p></div>}
function CoverageFlag({label,value}:{label:string;value:boolean|null}){const unavailable=value===null;return <div className={`rounded-xl border p-4 ${unavailable?"border-[#D9E0E9] bg-[#F6F8FB]":value?"border-[#B6DFD1] bg-[#F0FAF6]":"border-[#EDC5CA] bg-[#FDF3F4]"}`}><p className="text-[10px] uppercase tracking-[.08em] text-[#8491A2]">{label}</p><p className={`mt-2 flex items-center gap-2 text-sm font-semibold ${unavailable?"text-[#657489]":value?"text-[#087B57]":"text-[#A14450]"}`}>{unavailable?<AlertTriangle size={16}/>:value?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>} {unavailable?"Policy dates unavailable":value?"Yes":"No"}</p></div>}
function ErrorText({children}:{children?:string}){return children?<p role="alert" className="mt-2 text-[11px] font-medium text-[#A14450]">{children}</p>:null}
