import type {FinalizedClaim} from "./claim-types";
import {documentedLoss} from "./claim-types";
import {isDateWithinInclusivePeriod,normalizeDateOnly} from "./policy-date";
export {finalizeDecision,isDecisionValid,normalizeFinalizedDecision,outcomeStatus} from "./decision-status";
export type DecisionWorkflowStatus="Submitted"|"Evidence Review"|"Coverage Analysis"|"Decision Ready"|"Approved"|"Partially Approved"|"More Evidence Required"|"Rejected";
export type EvidenceReviewStatus="Unverified"|"Verified"|"Reviewed"|"Needs attention"|"Rejected evidence";export type EvidenceRelevance="High"|"Medium"|"Low";export type DecisionChoice="Approve"|"Partial approval"|"Request more evidence"|"Reject";
export type EvidenceReview={evidenceId:string;status:EvidenceReviewStatus;relevance:EvidenceRelevance;reviewerNote:string;updatedAt:string};export type DecisionActivity={id:string;type:string;message:string;createdAt:string};
export type CoverageAnalysis={policyActive:boolean|null;incidentWithinCoveragePeriod:boolean|null;policyDatesAvailable:boolean;requestedAmount:number;documentedLoss:number;deductible:number;coverageLimit:number;eligibleLoss:number;netEligibleAmount:number;completedAt:string|null};
export type ClaimDecision={claimId:string;createdAt:string;updatedAt:string;workflowStatus:DecisionWorkflowStatus;choice:DecisionChoice|null;recommendedSettlement:number;rationale:string;internalNotes:string;requiredEvidenceMessage:string;evidenceReviews:EvidenceReview[];coverage:CoverageAnalysis;activities:DecisionActivity[]};
export function calculateCoverage(claim:FinalizedClaim):CoverageAnalysis{const loss=documentedLoss(claim);const incidentDate=claim.incident?.incidentDate;const policyStartDate=claim.policy?.policyStartDate;const policyEndDate=claim.policy?.policyEndDate;const policyDatesAvailable=Boolean(normalizeDateOnly(incidentDate??"")&&normalizeDateOnly(policyStartDate??"")&&normalizeDateOnly(policyEndDate??""));const incidentWithin=policyDatesAvailable?isDateWithinInclusivePeriod(incidentDate,policyStartDate,policyEndDate):null;const eligibleLoss=Math.min(loss,Math.max(claim.policy.coverageLimit,0));return{policyActive:incidentWithin,incidentWithinCoveragePeriod:incidentWithin,policyDatesAvailable,requestedAmount:claim.financialLoss.requestedAmount,documentedLoss:loss,deductible:claim.policy.deductible,coverageLimit:claim.policy.coverageLimit,eligibleLoss,netEligibleAmount:Math.max(eligibleLoss-claim.policy.deductible,0),completedAt:null}}
export function createDecision(claim:FinalizedClaim):ClaimDecision{const now=new Date().toISOString();return{claimId:claim.id,createdAt:now,updatedAt:now,workflowStatus:"Submitted",choice:null,recommendedSettlement:0,rationale:"",internalNotes:"",requiredEvidenceMessage:"",evidenceReviews:[],coverage:calculateCoverage(claim),activities:[]}}
export function decisionStatusForClaim(decision:ClaimDecision|undefined):DecisionWorkflowStatus{return decision?.workflowStatus??"Submitted"}
